nameOverride: ""
fullnameOverride: ""

imagePullSecrets: []

core:
  internalUrl: http://osrd-core.osrd.svc.cluster.local
  enabled: true
  image: osrd/core
  pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  annotations: {}
  labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  env: []

editoast:
  internalUrl: http://osrd-editoast.osrd.svc.cluster.local
  enabled: true
  image: osrd/editoast
  pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  annotations: {}
  init:
    enabled: true
    extend: ""
  labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  env: []

tileServer:
  internalUrl: http://osrd-tile-server.osrd.svc.cluster.local
  enabled: false
  image: osrd/editoast
  pullPolicy: IfNotPresent
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  hpa:
    enabled: false
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80
  annotations: {}
  labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  env: []

gateway:
  enabled: true
  image: osrd/gateway
  pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
  ingress:
    enabled: false
    className: ""
    domains:
      - osrd.local
    secretName: osrd-gateway-tls
    annotations: {}
    tls: []
  annotations: {}
  labels: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  resources: {}
  env: []
  volumes: []
  volumeMounts: []
  config:
    auth:
      providers:
        - type: "Mocked"
          provider_id: "mocked"
          username: "osrd-admin"
          require_login: false
    trusted_proxies:
      - "10.0.0.0/8"
      - "172.16.0.0/12"
      - "192.168.0.0/16"
