{{- if .Values.services.gateway.extrahelp }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osrd.fullname" . }}-gateway-extrahelp
data:
  help.md: |
    {{ .Values.services.gateway.extrahelp | nindent 4 }}
{{- end }}
