{{- if .Values.core.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osrd.fullname" . }}-core
  labels:
    {{- include "osrd.labels.core" . | nindent 4 }}
spec:
  replicas: {{ .Values.core.replicaCount }}
  selector:
    matchLabels:
      {{- include "osrd.selectorLabels.core" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.core.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osrd.labels.core" . | nindent 8 }}
	      {{- with .Values.core.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-core
          image: "{{ .Values.core.image }}"
          imagePullPolicy: {{ .Values.core.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.core.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            {{- range $key, $value := .Values.core.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            - name: MIDDLEWARE_BASE_URL
              value: {{ .Values.editoast.internalUrl }}
            - name: CORE_PORT
              value: "{{ .Values.core.service.targetPort }}"
          resources:
            {{- toYaml .Values.core.resources | nindent 12 }}
      {{- with .Values.core.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.core.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
