{{- if .Values.editoast.init.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "osrd.fullname" . }}-editoast-init
data:
  script.sh: |
    #!/bin/sh
    set -e
    
    {{- with .Values.editoast.init.extend }}
    {{ . }}
    {{- end }}
    diesel migration run
{{- end }}
