{{- if .Values.editoast.init.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "osrd.fullname" . }}-editoast-init
  labels:
    name: {{ include "osrd.fullname" . }}-editoast-init
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Never
      containers:
        - name: {{ .Chart.Name }}-editoast-migrate
          image: "{{ .Values.editoast.image }}"
          imagePullPolicy: {{ .Values.editoast.pullPolicy }}
          command: ["/bin/sh"]
          args: ["/init-vol/script.sh"]
          env:
            {{- with .Values.editoast.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: EDITOAST_PORT
              value: "{{ .Values.editoast.service.targetPort }}"
            - name: OSRD_BACKEND_URL
              value: {{ .Values.core.internalUrl }}
          volumeMounts:
            - name: config
              mountPath: /init-vol/script.sh
              subPath: script.sh
      volumes:
        - name: config
          configMap:
            name: {{ include "osrd.fullname" . }}-editoast-init
  backoffLimit: 4
{{- end }}
