{{- if .Values.gateway.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osrd.fullname" . }}-gateway
  labels:
    {{- include "osrd.labels.gateway" . | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "osrd.selectorLabels.gateway" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.gateway.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "osrd.labels.gateway" . | nindent 8 }}
	      {{- with .Values.gateway.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-gateway
          image: "{{ .Values.gateway.image }}"
          imagePullPolicy: {{ .Values.gateway.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: config
              mountPath: /config
              subPath: gateway.toml
          env:
            {{- with .Values.editoast.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: MIDDLEWARE_BASE_URL
              value: {{ .Values.editoast.internalUrl }}
            - name: PORT
              value: "{{ .Values.gateway.service.port }}"
          resources:
            {{- toYaml .Values.gateway.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "osrd.fullname" . }}-gateway-config
      {{- with .Values.gateway.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.gateway.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
