{{- if .Values.images.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osrd.fullname" . }}-images
  labels:
    {{- include "osrd.labels.images" . | nindent 4 }}
  {{- with .Values.images.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.images.replicaCount }}
  selector:
    matchLabels:
      {{- include "osrd.selectorLabels.images" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.images.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "osrd.labels.images" . | nindent 8 }}
        {{- with .Values.images.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
