apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "osrd.fullname" . }}-osrdyne-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "osrd.fullname" . }}-osrdyne-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "osrd.fullname" . }}-osrdyne-role
  apiGroup: rbac.authorization.k8s.io
