apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osrd.fullname" . }}-osrdyne-sa
  labels:
    app.kubernetes.io/name: {{ include "osrd.name" . }}
    helm.sh/chart: {{ include "osrd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
