{{- if .Values.osrdyne.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osrd.fullname" . }}-osrdyne
  labels:
    {{- include "osrd.labels.osrdyne" . | nindent 4 }}
  {{- with .Values.osrdyne.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "osrd.selectorLabels.osrdyne" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.osrdyne.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "osrd.labels.osrdyne" . | nindent 8 }}
        {{- with .Values.osrdyne.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "osrd.fullname" . }}-osrdyne-sa
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "osrd.name" . }}-osrdyne
          image: "{{ .Values.osrdyne.image }}"
          imagePullPolicy: {{ .Values.osrdyne.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.osrdyne.service.port }}
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /osrdyne.yml
              subPath: osrdyne.yml
            {{- with .Values.osrdyne.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            {{- with .Values.osrdyne.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: RUST_LOG
              value: info
            - name: OSRDYNE_PORT
              value: "{{ .Values.osrdyne.service.port }}"
          resources:
            {{- toYaml .Values.osrdyne.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "osrd.fullname" . }}-osrdyne-config
        {{- with .Values.osrdyne.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.osrdyne.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.osrdyne.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.osrdyne.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
