apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "osrd.fullname" . }}-osrdyne-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "delete", "list"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "create", "update", "delete", "list"]
