apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "osrd.fullname" . }}-osrdyne-role
  namespace: {{ .Release.Namespace }}
rules:
# Manage deployments
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "create", "update", "delete", "list"]
# Manage autoscaling
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "create", "update", "delete", "list"]
# Manage keda scaled objects
- apiGroups: ["keda.sh"]
  resources: ["scaledobjects"]
  verbs: ["get", "create", "update", "delete", "list"]
