{{- if .Values.tileServer.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "osrd.fullname" . }}-tile-server
  labels:
    {{- include "osrd.labels.tileServer" . | nindent 4 }}
  {{- with .Values.tileServer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.tileServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "osrd.selectorLabels.tileServer" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
        {{- with .Values.tileServer.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "osrd.labels.tileServer" . | nindent 8 }}
        {{- with .Values.tileServer.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-tile-server
          image: "{{ .Values.tileServer.image }}"
          imagePullPolicy: {{ .Values.tileServer.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.tileServer.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
            {{- with .Values.tileServer.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: EDITOAST_PORT
              value: "{{ .Values.tileServer.service.targetPort }}"
            - name: OSRD_BACKEND_URL
              value: {{ .Values.core.internalUrl }}
          resources:
            {{- toYaml .Values.tileServer.resources | nindent 12 }}
      {{- with .Values.tileServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tileServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tileServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

{{- end }}
