{{- if .Values.tileServer.hpa.enabled -}}

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "osrd.fullname" . }}-tile-server-hpa
spec:
  maxReplicas: {{ .Values.tileServer.hpa.maxReplicas }}
  minReplicas: {{ .Values.tileServer.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "osrd.fullname" . }}-tile-server
  targetCPUUtilizationPercentage: {{ .Values.tileServer.hpa.targetCPUUtilizationPercentage }}

{{- end }}
