{{- if .Values.services.editoast.hpa.enabled -}}

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "osrd.fullname" . }}-editoast-hpa
spec:
  maxReplicas: {{ .Values.services.editoast.hpa.maxReplicas }}
  minReplicas: {{ .Values.services.editoast.hpa.minReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "osrd.fullname" . }}-editoast
  targetCPUUtilizationPercentage: {{ .Values.services.editoast.hpa.targetCPUUtilizationPercentage }}

{{- end }}
