name: Lint and build the chart

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Set Name and Version
      run: |
        CHART_NAME="osrd-dev"
        CHART_VERSION="0.1.${{ github.run_id }}"
        echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
        echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
        sed -i "s/NAME_REPLACE_ME/$CHART_NAME/" ./Chart.yaml
        sed -i "s/VERSION_REPLACE_ME/$CHART_VERSION/" ./Chart.yaml

    - name: Lint Helm Chart
      run: helm lint .

    - name: Package the Chart
      run: |
        helm package .
