name: Publish Helm Chart to GHCR

on:
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set Name and Version
        run: |
          CHART_NAME="osrd-dev"
          CHART_VERSION="0.1.${{ github.run_id }}"
          if [ "${{ github.event_name }}" = "release" ]; then
            CHART_NAME="osrd"
            CHART_VERSION="${{ github.event.release.tag_name }}"
          fi
          echo "CHART_NAME=$CHART_NAME" >> $GITHUB_ENV
          echo "CHART_VERSION=$CHART_VERSION" >> $GITHUB_ENV
          sed -i "s/NAME_REPLACE_ME/$CHART_NAME/" ./Chart.yaml
          sed -i "s/VERSION_REPLACE_ME/$CHART_VERSION/" ./Chart.yaml

      - name: Lint Helm Chart
        run: helm lint .

      - name: Save and Push Helm Chart to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login ghcr.io -u ${{ github.actor }} --password-stdin
          helm package .
          echo "Pushing to oci://ghcr.io/openrailassociation/${CHART_NAME}:v${CHART_VERSION}"
          helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://ghcr.io/openrailassociation/osrd-charts
